### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by 7sorkr** [MauriceVeraart/XLStoCCG#45]
hello

It doesn't work well when compiling.

Is there a way..?

npm ERR! code 1
npm ERR! path C:\electron-vue\XLStoCCG\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\electron-vue\XLStoCCG\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\electron-vue\\XLStoCCG\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.10.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\electron-vue\XLStoCCG\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\electron-vue\XLStoCCG\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\electron-vue\XLStoCCG\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\electron-vue\XLStoCCG\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\electron-vue\XLStoCCG\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\electron-vue\XLStoCCG\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\electron-vue\XLStoCCG\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\electron-vue\XLStoCCG\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\electron-vue\XLStoCCG\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\electron-vue\XLStoCCG\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\electron-vue\XLStoCCG\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\electron-vue\XLStoCCG\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python312\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python312\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\electron-vue\\XLStoCCG\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\electron-vue\XLStoCCG\node_modules\node-sass
npm ERR! gyp ERR! node -v v20.10.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by MauriceVeraart** [comment]
Hi
I am not activly working on this code soo it's a bit old and not the best.
But i tried to build it and it indeed failed the firsttime.
By using nvm and go back to node version 10.13.0 it does work on my side.
If you just want to have a quick look 

i uploaded a release
https://github.com/MauriceVeraart/XLStoCCG/releases/tag/beta

grt
Maurice

**Comment by 7sorkr** [comment]
Thank you Maurice.

You are a great client.

If I enter new data in Excel and save it, can the DATA value be updated in XLStoCCG?

Do I have to press the LOAD button every time?
![XLStoCCG](https://github.com/MauriceVeraart/XLStoCCG/assets/32606306/ef95663f-1e0a-4473-87d6-186375f94906)

**Comment by MauriceVeraart** [comment]
Yes you have to load.
It was ment to be used in a fashion that the excel was produced in pre-production.

Not during the broadcast / in realtime.

I think this date.picker in "template" should not be there.
I will remove that as it does not make any sense ;)
i think it is the result of a experiment LOL

if it is usefull for you feel free to use it

grt
Maurice

**Comment by MauriceVeraart** [comment]
see release without timepicker
